trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Host
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
      displayName: 'Terraform init (Backend State)'
      inputs:
        backendServiceArm: 'Azure Pass - Sponsorship (4f4be271-bdd8-44e4-9825-bfdfbc87d62a)'
        backendAzureRmResourceGroupName: tfstate
        backendAzureRmStorageAccountName: tfstatejoey
        backendAzureRmContainerName: tfstate
        backendAzureRmKey: tf/staging.tfstate
