---
- hosts: servers
  become: yes
  gather_facts: yes
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: "Add nodejs 14.x ppa for apt repo"
      apt_repository:
        repo: https://deb.nodesource.com/setup_14.x

    - name: "Install nodejs"
      apt:
        update_cache: yes
        name: nodejs
        state: present
